# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ml_metadata/simple_types/proto/simple_types.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ml_metadata.proto import metadata_store_pb2 as ml__metadata_dot_proto_dot_metadata__store__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1ml_metadata/simple_types/proto/simple_types.proto\x12\x0bml_metadata\x1a&ml_metadata/proto/metadata_store.proto\"\xa6\x01\n\x0bSimpleTypes\x12\x31\n\x0e\x61rtifact_types\x18\x01 \x03(\x0b\x32\x19.ml_metadata.ArtifactType\x12\x33\n\x0f\x65xecution_types\x18\x02 \x03(\x0b\x32\x1a.ml_metadata.ExecutionType\x12/\n\rcontext_types\x18\x03 \x03(\x0b\x32\x18.ml_metadata.ContextTypeb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ml_metadata.simple_types.proto.simple_types_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SIMPLETYPES._serialized_start=107
  _SIMPLETYPES._serialized_end=273
# @@protoc_insertion_point(module_scope)
